#!/usr/bin/env python3

import gym
import numpy as np
import rospy as rp
import tqdm
from env_config import config


def main():
    env = gym.make("menge_gym:MengeGym-v0")
    env.configure(config.BaseEnvConfig)
    env.setup_ros_connection()
    env.reset()
    num_iterations = 200
    action_sequence = 20 * [np.array([env.action_space.nvec[0] - 1, np.median(range(env.action_space.nvec[1]))],
                                     dtype=np.int32)] + [np.array([0, env.action_space.nvec[1] - 1])] \
                      + 20 * [np.array([env.action_space.nvec[0] - 1, np.median(range(env.action_space.nvec[1]))],
                                       dtype=np.int32)] + 3 * [np.array([0, 0])] \
                      + 20 * [np.array([env.action_space.nvec[0] - 1, np.median(range(env.action_space.nvec[1]))],
                                       dtype=np.int32)] + 4 * [np.array([0, 0])] \
                      + 32 * [np.array([np.median(range(env.action_space.nvec[0])),
                                        np.percentile(range(env.action_space.nvec[1]), 40)], dtype=np.int32)]
    try:
        with tqdm.trange(num_iterations) as t:
            for step in t:
                if step < 100:
                    action = action_sequence[step]
                else:
                    action = env.action_space.sample()
                ob, reward, done, info = env.step(action)
                if done:
                    rp.loginfo(info)
                    rp.loginfo('Finished cleanly')
                    env.reset()
                    rp.loginfo('Set up new env')
                else:
                    rp.loginfo('Reward: %f' % reward)
                env.render()
        rp.loginfo('Done with all iterations')
        env.close()
    except KeyboardInterrupt:
        env.close()
    except Exception as e:
        env.close()
        print('Exception in main script')
        raise e


if __name__ == "__main__":
    main()
